# # TODO: does not work in linux
# cc_binary(
#     name = "hello_libxsmm",
#     srcs = [
#           "hello_libxsmm.cc",
#     ],
#     deps = [
#         # "//external:glog",
#         "//external:xsmm_avx",
#     ],
#     visibility = ["//visibility:public"],
# )
