package(default_visibility = ["//visibility:public"])

cc_proto_library(
    name = "latlng",
    deps = [
      ":latlng_proto",
    ],
)

proto_library(
    name = "latlng_proto",
    srcs = [
      "latlng.proto",
    ],
)


