dist: trusty
sudo: required

# temp disable cache
cache:
  directories:
    - $HOME/mc
    - $HOME/.cache/bazel

before_cache:
  - rm -f bazel-*
  - rm -rf $HOME/.cache/bazel/_bazel_travis/install

language: c++

addons:
  apt:
    packages:
      # - oracle-java8-installer
      # - oracle-java8-set-default
      - doxygen # see http://bit.ly/2T7EmhT for some introduction
      - doxygen-doc
      - doxygen-latex
      - doxygen-gui
      - graphviz

# JDK configuration, ref: https://github.com/travis-ci/travis-ci/issues/2316
matrix:
  include:
    - os: linux # linux + clang
      jdk: oraclejdk8
      env:
        - CACHE_NAME=linux
      compiler:
        - clang

    - os: linux # linux + gcc-5
      jdk: oraclejdk8
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env:
        - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
        - CACHE_NAME=linux

    - os: linux # linux + gcc-6
      jdk: oraclejdk8
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
        - CACHE_NAME=linux

    - os: linux # linux + gcc-7
      jdk: oraclejdk8
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
        - CACHE_NAME=linux

    - os: osx
      osx_image: xcode8.3 # Building Bazel requires JDK8.
      env:
        - CACHE_NAME=osx
      compiler:
        - clang

before_install:
  - if [[ ! -z "${MATRIX_EVAL}" ]]; then eval "${MATRIX_EVAL}" ; fi
  # debug
  - . .github/travis/before_install.sh
  - pwd # check current dir, result: /home/travis/build/yuikns/argcv
  - echo $PATH
  - df -h
  - date
  - uname -a
  - python -V

install:
  - . .github/travis/install.sh
  - echo $PATH
  # configure python
  - bazel fetch //...

script:
  # build by stage for cache
  # - bazel build //...
  - make
  # - bazel build //external:nasm
  # test if there is any library missing
  # - bazel run //examples/c/libxml2:gjobread $(pwd)/examples/c/libxml2/gjobs.xml
  # - bazel run //examples/cxx/libxml2:gjobread $(pwd)/examples/c/libxml2/gjobs.xml
  # - bazel test --genrule_strategy=standalone --spawn_strategy=standalone  //...
  # - bazel test  --test_output=errors //...
  - make test-all

# temporary stop deploying
# deploy:
#   # deploy master to production
#   - provider: script
#     keep-history: true
#     skip-cleanup: false
#     script: .github/travis/deploy.sh
#     on:
#       branch: master

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/8d14bff0d2d10ace5289 # argcv
      - https://webhooks.gitter.im/e/74810b212d49d753d9a2 # argcv/argcv
    on_success: always # options: [always|never|change] default: always
    on_failure: always # options: [always|never|change] default: always
    on_start: always # options: [always|never|change] default: always

