cc_binary(
    name = "hello_gflags",
    srcs = [
          "hello_gflags.cc",
    ],
    deps = [
        "//external:glog",
        "//external:gflags",
    ],
    visibility = ["//visibility:public"],
)
