# Note: Timer is moved to par
cc_binary(
    name = "example_timer",
    srcs = [
          "example_timer.cc",
    ],
    deps = [
        "//argcv/cxx:par",
        "//external:glog",
    ],
    visibility = ["//visibility:public"],
)
