cc_binary(
    name = "dynamic_thread_pool",
    srcs = [
          "main.cc"
    ],
    deps = [
        "//external:glog",
        "//argcv/cxx:par",
    ],
    visibility = ["//visibility:public"],
)
