cc_binary(
    name = "gjobread",
    srcs = [
      "gjobread.cc",
    ],
    deps = [
        "//external:glog",
        "//argcv/cxx/encoding:xml",
    ],
    visibility = ["//visibility:public"],
)

