cc_binary(
    name = "hello_absl",
    srcs = [
          "main.cc",
    ],
    deps = [
        "//external:glog",
        "//external:absl/strings",
    ],
    visibility = ["//visibility:public"],
)