cc_binary(
    name = "echo_server",
    srcs = [
          "echo_server.cc",
    ],
    deps = [
        "//argcv/cxx:net",
        "//external:glog",
    ],
    visibility = ["//visibility:public"],
)
