# Copyright 2019 Yu Jing
licenses(["notice"])  # MIT

package(default_visibility = ["//visibility:public"])

cc_binary(
    name = "stb_c_lexer",
    srcs = [
        "stb_c_lexer.c",
    ],
    copts = [],
    deps = [
        "@com_github_nothings_stb//:stb",
    ],
)
