cc_binary(
    name = "example_cq",
    srcs = [
        "example_cq.cc",
    ],
    deps = [
        "//external:cqueue",
        "//external:glog",
        "//argcv/cxx:par",
    ],
    visibility = ["//visibility:public"],
)

cc_binary(
    name = "example_blk_cq",
    srcs = [
        "example_blk_cq.cc",
    ],
    deps = [
        "//external:cqueue",
        "//external:glog",
        "//argcv/cxx:par",
    ],
    visibility = ["//visibility:public"],
)

