package(default_visibility = ["//visibility:public"])

sh_library(
    name = "bash_helpers",
    data = [
        "bash_helpers.sh",
    ],
)

py_binary(
    name = "configure_file",
    srcs = [
      "configure_file.py",
    ],
)