cc_binary(
    name = "hello_eigen",
    srcs = [
          "hello_eigen.cc",
    ],
    deps = [
        "//external:glog",
        "//third_party/eigen3:eigen3",
    ],
    visibility = ["//visibility:public"],
)
